# Default initial positions for myarm_300_pi_thorgripper's ros2_control fake system

initial_positions:
  endeffector_gripper: 0
  joint1: 0
  joint2: 0
  joint3: 0
  joint4: 0
  joint5: 0
  joint6: 0
  joint7: 0