#!/usr/bin/env python3
"""
Build the reduced planning model from the full arm URDF.

The reduced model is the positioning sub-chain only:

    world -- base -- link1 -- link2 -- link3 -- link4 -- wrist_center
                  j1      j2      j3      j4         (fixed)

plus the swept wrist volume from wrist_blob_gen.py, hung off wrist_center
through two continuous "align" joints:

    wrist_center --[blob_align_x]-- blob_align_link --[blob_align_y]-- wrist_blob

WHY THE ALIGN JOINTS EXIST
--------------------------
The blob is the wrist assembly swept over the orientations the upright
constraint allows, and that constraint is stated in the WORLD frame: the tube
stays vertical no matter where the arm is. So the swept volume is a solid of
revolution about the world vertical, not about any axis fixed in link4.

Welding the blob rigidly to link4 would therefore be wrong -- as the arm moves,
link4 rotates, and a link4-fixed blob would rotate with it into orientations the
tube never actually takes. To stay correct you would have to fall back to the
full-SO(3) sphere, which is 237 mm in radius on an arm whose entire reach is
243 mm. Useless.

The two align joints fix that. They are NOT part of any planning group and the
sampler never touches them. The state validity checker sets them, at every state
it evaluates, to whatever keeps the blob's own z axis pointing along world z.
Because the blob is a solid of revolution about that axis, two joints are
exactly enough -- the third rotation is the symmetry axis and is free.

Generating rather than hand-writing this file keeps joints 1-4 bit-identical to
the real robot. Hand-copying them once is fine; keeping them in sync after a
URDF change is not.

USAGE
-----
  python3 make_reduced_model.py                       # 4-DOF, carry blob
  python3 make_reduced_model.py --blob naive          # the pessimistic sphere
  python3 make_reduced_model.py --geometry mesh       # STL blob, keeps the hole
"""

import argparse
import json
import os
import xml.etree.ElementTree as ET
from xml.dom import minidom

# The chain we keep. Everything distal of link4 is replaced by the blob.
KEEP_LINKS = ["world", "base", "link1", "link2", "link3", "link4"]
KEEP_JOINTS = ["virtual_fixed_joint", "joint1", "joint2", "joint3", "joint4"]

# The joint whose origin transform lands exactly on the wrist centre. joint5,
# joint6 and joint7 all pass through that point -- that is what makes the wrist
# spherical -- so joint5's origin IS the wrist centre.
WRIST_CENTRE_JOINT = "joint5"

ARM_LINKS = ["base", "link1", "link2", "link3", "link4"]


def pretty(elem):
    raw = ET.tostring(elem, "utf-8")
    out = minidom.parseString(raw).toprettyxml(indent="  ")
    return "\n".join(ln for ln in out.splitlines() if ln.strip())


def build_urdf(full_urdf, blob_json, geometry, blob_mesh_uri, robot_name,
               keep_everything=False):
    """
    keep_everything=False -> the planning model: base..link4 plus the blob.
    keep_everything=True  -> the PREVIEW model: the entire real arm, gripper and
                             all, plus the blob. Nothing plans against this one;
                             it exists so RViz can show the actual wrist moving
                             inside the volume that is meant to contain it. If
                             the ring ever fails to enclose the hand, that is
                             visible immediately.
    """
    src = ET.parse(full_urdf).getroot()
    out = ET.Element("robot", {"name": robot_name})
    out.append(ET.Comment(
        " GENERATED by tools/make_reduced_model.py. Do not edit by hand. "))

    kept_links = {L.get("name"): L for L in src.findall("link")}
    kept_joints = {j.get("name"): j for j in src.findall("joint")}

    if keep_everything:
        # Preserve document order so parents precede children.
        for child in src:
            if child.tag in ("link", "joint"):
                out.append(child)
    else:
        for name in KEEP_LINKS:
            if name not in kept_links:
                raise KeyError(f"link '{name}' missing from {full_urdf}")
            out.append(kept_links[name])

        for name in KEEP_JOINTS:
            if name not in kept_joints:
                raise KeyError(f"joint '{name}' missing from {full_urdf}")
            out.append(kept_joints[name])

    # --- wrist centre ------------------------------------------------------
    j5 = kept_joints[WRIST_CENTRE_JOINT]
    o5 = j5.find("origin")
    ET.SubElement(out, "link", {"name": "wrist_center"})
    jw = ET.SubElement(out, "joint", {"name": "wrist_center_fixed", "type": "fixed"})
    ET.SubElement(jw, "parent", {"link": j5.find("parent").get("link")})
    ET.SubElement(jw, "child", {"link": "wrist_center"})
    # joint5's FIXED origin (xyz and rpy) is kept, so wrist_center's z axis is
    # the joint5 axis. What is dropped is the VARIABLE q5 rotation -- we want a
    # frame that sits at the wrist centre without turning with the wrist.
    ET.SubElement(jw, "origin", {
        "xyz": o5.get("xyz", "0 0 0"),
        "rpy": o5.get("rpy", "0 0 0"),
    })

    # --- align joints ------------------------------------------------------
    ET.SubElement(out, "link", {"name": "blob_align_link"})
    for jname, parent, child, axis in (
        ("blob_align_x", "wrist_center", "blob_align_link", "1 0 0"),
        ("blob_align_y", "blob_align_link", "wrist_blob", "0 1 0"),
    ):
        j = ET.SubElement(out, "joint", {"name": jname, "type": "continuous"})
        ET.SubElement(j, "parent", {"link": parent})
        ET.SubElement(j, "child", {"link": child})
        ET.SubElement(j, "origin", {"xyz": "0 0 0", "rpy": "0 0 0"})
        ET.SubElement(j, "axis", {"xyz": axis})

    # --- the blob itself ---------------------------------------------------
    blob = ET.SubElement(out, "link", {"name": "wrist_blob"})
    prof = json.load(open(blob_json))

    if geometry == "mesh":
        for tag in ("visual", "collision"):
            e = ET.SubElement(blob, tag)
            g = ET.SubElement(e, "geometry")
            ET.SubElement(g, "mesh", {"filename": blob_mesh_uri})
        n_shapes = 1
    else:
        bands = []
        for b in prof["profile"]:
            if bands and abs(bands[-1][2] - b["r_out"]) < 0.006:
                bands[-1] = (bands[-1][0], b["z1"], max(bands[-1][2], b["r_out"]))
            else:
                bands.append((b["z0"], b["z1"], b["r_out"]))
        for (z0, z1, r) in bands:
            for tag in ("visual", "collision"):
                e = ET.SubElement(blob, tag)
                ET.SubElement(e, "origin",
                              {"xyz": f"0 0 {(z0 + z1) / 2:.6f}", "rpy": "0 0 0"})
                g = ET.SubElement(e, "geometry")
                ET.SubElement(g, "cylinder",
                              {"radius": f"{r:.6f}", "length": f"{z1 - z0:.6f}"})
        n_shapes = len(bands)

    # A link with no inertia is fine for planning, but some tools warn. Give the
    # blob a token mass so the model loads clean everywhere.
    inert = ET.SubElement(blob, "inertial")
    ET.SubElement(inert, "mass", {"value": "0.001"})
    ET.SubElement(inert, "inertia", {"ixx": "1e-6", "ixy": "0", "ixz": "0",
                                     "iyy": "1e-6", "iyz": "0", "izz": "1e-6"})

    return out, n_shapes, prof


def build_srdf(robot_name, dof, full_srdf):
    out = ET.Element("robot", {"name": robot_name})
    out.append(ET.Comment(
        " GENERATED by tools/make_reduced_model.py. Do not edit by hand. "))

    # The planning group. 4-DOF keeps joint3, the arm-angle redundancy; 3-DOF
    # locks it, which costs ~5% of the wrist-centre workspace (measured) and
    # buys a genuinely 3-dimensional search.
    g4 = ET.SubElement(out, "group", {"name": "arm_positioning"})
    for jn in ["joint1", "joint2", "joint3", "joint4"]:
        ET.SubElement(g4, "joint", {"name": jn})

    g3 = ET.SubElement(out, "group", {"name": "arm_positioning_3dof"})
    for jn in ["joint1", "joint2", "joint4"]:
        ET.SubElement(g3, "joint", {"name": jn})

    st = ET.SubElement(out, "group_state", {"name": "home", "group": "arm_positioning"})
    for jn in ["joint1", "joint2", "joint3", "joint4"]:
        ET.SubElement(st, "joint", {"name": jn, "value": "0"})

    # The align joints are driven by the validity checker, never by a planner.
    for jn in ("blob_align_x", "blob_align_y"):
        ET.SubElement(out, "passive_joint", {"name": jn})

    # Carry over every disabled pair among the links we kept, so self-collision
    # behaves exactly as it does on the full model.
    src = ET.parse(full_srdf).getroot()
    kept = set(ARM_LINKS)
    n_carried = 0
    for dc in src.findall("disable_collisions"):
        if dc.get("link1") in kept and dc.get("link2") in kept:
            ET.SubElement(out, "disable_collisions", dict(dc.attrib))
            n_carried += 1

    # The blob never self-collides with the arm. On the real robot the wrist
    # assembly cannot reach any arm link either -- every link7/gripper pair in
    # the full SRDF is already marked "Never". Leaving these enabled would make
    # the blob, which always engulfs link4, report a permanent self-collision.
    for L in ARM_LINKS + ["wrist_center", "blob_align_link"]:
        ET.SubElement(out, "disable_collisions",
                      {"link1": "wrist_blob", "link2": L,
                       "reason": "swept-volume surrogate"})

    return out, n_carried


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ws_src = os.path.abspath(os.path.join(here, "..", ".."))
    gen = os.path.join(here, "..", "generated")

    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--urdf", default=os.path.join(
        ws_src, "myarm_300_pi", "urdf", "myarm_300_pi_thorgripper.urdf"))
    ap.add_argument("--srdf", default=os.path.join(
        ws_src, "robot_config", "config", "myarm_300_pi_thorgripper.srdf"))
    ap.add_argument("--blob", default="carry", help="blob tag from wrist_blob_gen.py")
    ap.add_argument("--geometry", choices=("cylinders", "mesh"), default="cylinders",
                    help="cylinders are solid (fills the ring's hole, more "
                         "conservative); mesh keeps the hole")
    ap.add_argument("--out-dir", default=gen)
    ap.add_argument("--name", default="myarm_reduced")
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    blob_json = os.path.join(args.out_dir, f"wrist_blob_{args.blob}.json")
    if not os.path.exists(blob_json):
        raise SystemExit(f"missing {blob_json}\nrun wrist_blob_gen.py --tag {args.blob} first")

    mesh_uri = f"package://my_robot_control/generated/wrist_blob_{args.blob}.stl"
    urdf, n_shapes, prof = build_urdf(args.urdf, blob_json, args.geometry,
                                      mesh_uri, args.name)
    srdf, n_carried = build_srdf(args.name, 4, args.srdf)

    u_path = os.path.join(args.out_dir, "reduced_arm.urdf")
    s_path = os.path.join(args.out_dir, "reduced_arm.srdf")
    open(u_path, "w").write(pretty(urdf) + "\n")
    open(s_path, "w").write(pretty(srdf) + "\n")

    # The preview model: whole arm plus the blob, for looking at in RViz.
    preview, _, _ = build_urdf(args.urdf, blob_json, args.geometry, mesh_uri,
                               args.name + "_preview", keep_everything=True)
    p_path = os.path.join(args.out_dir, "preview_arm.urdf")
    open(p_path, "w").write(pretty(preview) + "\n")

    print(f"blob        : {args.blob}  ({prof['mode']}, tilt={prof['tilt_tolerance']})")
    print(f"              radius {prof['max_radius']*1000:.1f} mm, "
          f"z {prof['z_min']*1000:.1f}..{prof['z_max']*1000:.1f} mm")
    print(f"geometry    : {args.geometry} ({n_shapes} shape(s))")
    print(f"carried over: {n_carried} disable_collisions pairs from the full SRDF")
    print(f"wrote {u_path}")
    print(f"wrote {s_path}")
    print(f"wrote {p_path}  (whole arm + blob, for RViz)")


if __name__ == "__main__":
    main()
